spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cohort26
    username: postgres
    password: root
logging:
  file:
    name: hello-liquibase.log
  level:
    spring: INFO